version: '3'
services:
    database:
        image: mysql:8.0
        container_name: database
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=WngvzAmb
            - MYSQL_DATABASE=abc
            - MYSQL_USER=testuser
            - MYSQL_PASSWORD=WngvzAmb
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "13306:3306"
    webserver:
        image: eboraas/laravel
        container_name: webserver
        ports:
            - "180:80"
#            - "1443:443"
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=database
            - DB_PORT=3306
            - DB_DATABASE=abc
            - DB_USERNAME=root
            - DB_PASSWORD=WngvzAmb
        depends_on:
            - database
        volumes:
            - ./app/:/var/www/laravel/app/
            - ./public/:/var/www/laravel/public/
            - ./resources/:/var/www/laravel/resources/
            - ./routes/:/var/www/laravel/routes/
            - ./database/:/var/www/laravel/database/
            - ./tests/:/var/www/laravel/tests/
            - ./.env:/var/www/laravel/.env
